<form method="post" name="mini-login-form" id="mini-login-form">
  <label for="mini-username"><?php echo $this->__('Email Address'); ?></label>

  <div class="input-box">
    <input type="text" name="login[username]" class="required-entry input-text" id="mini-username"/>
  </div>
  <label for="mini-password"><?php echo $this->__('Password'); ?></label>

  <div class="input-box">
    <input type="password" name="login[password]" class="required-entry input-text" id="mini-password"/>
  </div>
  <div class="actions">
    <button class="button" type="button" onclick="close_popup('login-form-popup')">
      <span><span><?php echo $this->__('Close'); ?></span></span></button>
    <button class="button right" id="login-form-button" type="button">
      <span><span><?php echo $this->__('Log In'); ?></span></span></button>
  </div>
</form>